### ISSUE TITLE
sqlite3 dependency conflict when running bin/test in Rails 6

### ISSUE THREAD

**Issue by Inkybro** [penguinwokrs/firebase-auth-rails#8]
I see that the sqlite3 gem version required for rails 6 is 1.4, where the other versions of rails use lower version(s).

Unfortunately, this is causing a conflict when I try to run `bin/test`:

`can't activate sqlite3 (~> 1.4), already activated sqlite3-1.3.13. Make sure all dependencies are added to Gemfile.`

I'm trying to figure out how to fix it now, and will open a PR if I'm able. Any hints you may have would be helpful.

It seems like we need to somehow force it to *unload* the older version in a rails 6 environment, before it attempts to load sqlite3 1.4, but I honestly have no idea how to go about this, so again if you can point me in the right direction that'd be awesome!

**EDIT:** It seems like what is happening is that sqlite ~1.3 is specified as a dev dependency in the gemspec, so when I'm running `bin/test` perhaps it is loading that, causing the later conflict? Do we really need it as a development dependency when we load it from the `gemfiles/` files anyway?

Thanks!

**Comment by penguinwokrs** [comment]
@Inkybro 
Thank you!

very grateful for your changes.
I think it's good code, so merge.

**Comment by Inkybro** [comment]
@penguinwokrs happy to help!
